version: "3.9"

services:
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: kabu_db
      MYSQL_USER: kabu
      MYSQL_PASSWORD: kabu
      TZ: "Asia/Tokyo"
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/data:/var/lib/mysql
      - ./db/scripts:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: "sh -c 'sleep 10 && node server.js'"
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: mysql://kabu:kabupassword@db:3306/kabu_db
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - back_node_modules:/app/node_modules
    tty: true
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend/app:/app # frontend/appディレクトリをコンテナの/appにマウント
      - front_node_modules:/app/node_modules
    tty: true

volumes:
  front_node_modules:
  back_node_modules: